version: !!str 3
services:
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    expose:
        - "9100"
    network_mode: host
    pid: host
    volumes:
        - /:/host:ro,rslave
    command:
        - --path.rootfs=/host
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
        - 9090:9090
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
        - 8080:8080
    volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
        - 3000:3000
    volumes:
        - grafana_data:/var/lib/grafana
  fluentbit:
    container_name: fluentbit
    image: fluent/fluent-bit
    ports:
      - 24224:24224
      - 2020:2020
    command:
      - /fluent-bit/bin/fluent-bit
      - -c
      - /fluent-bit.conf
    volumes:
      - ./fluentbit.conf:/fluent-bit.conf
      - ./parsers.conf:/parsers.conf
      
  nginx:
    container_name: nginx
    image: nginx
    ports:
        - 80:80
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    logging:
       driver: fluentd
       options:
          fluentd-address: 10.5.1.169:24224
          tag: docker-nginx-{{.ID}}

  redis:
     container_name: redis
     image: redis:latest
     ports:
         - 6379:6379
  redis-exporter:
    image: oliver006/redis_exporter
    ports:
      - 9121:9121
    environment:
      REDIS_ADDR: "redis:6379"

  nginx-exporter:
    container_name: exporter-nginx
    image: nginx/nginx-prometheus-exporter:0.10.0
    ports:
        - 9113:9113
    command:
      - -nginx.scrape-uri=http://10.5.1.169:80/metrics
  loki:
    container_name: loki_database
    image: grafana/loki
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
volumes:
  prometheus_data:
  grafana_data:
  loki_data:

