global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
  scrape_timeout: 15s
  
#rule_files:
#  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['10.5.1.169:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: 
            - cadvisor:8080
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['10.5.1.169:9113']
  - job_name: redis-exporter
    static_configs:
      - targets: ['redis-exporter:9121']

