{
 "title": "REDIS",
 "time": { "from": "now-30s", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "selectdb",
    "query": {
     "query": "label_values(redis_db_keys{db=~\".+\"}, db)"
    }
   },
   {
    "name": "container_name",
    "query": {
     "query": "label_values(container_last_seen{name=~\".+\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "FileSystem_Input_Output",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "container_fs_io_current{name=~\"$container_name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Cpu-System",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 10, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "container_cpu_system_seconds_total{name=~'$container_name'}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "FIlesytem_Usage",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "container_fs_usage_bytes{name=~\"$container_name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "Logging", "type": "logs", "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 } },
  {
   "title": "Total Request",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 7, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "nginx_http_requests_total - nginx_connections_accepted",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Accept",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_accepted", "legendFormat": "__auto" }
   ]
  },
  { "title": "Nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Redis-System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "selectdb",
   "collapsed": true,
   "panels": [
    {
     "title": "total_read_processed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
     "targets": [
      { "expr": "redis_total_reads_processed", "legendFormat": "{{label_name}}" }
     ]
    },
    {
     "title": "memory-usage",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(redis_memory_used_bytes[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "NUMBER_KEY_TOTAL",
     "type": "stat",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "redis_db_keys{db=~\"$selectdb\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "EXPIRE_KEY",
     "type": "stat",
     "gridPos": { "h": 9, "w": 5, "x": 6, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "redis_expired_keys_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "NUMBER_CLIENT_CONNECT",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 11, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "redis_connected_clients", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Number of connections rejected because of maxclients limit",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 15, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "redis_rejected_connections_total",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "UP_TIME_MINUTE",
     "type": "stat",
     "description": "Redis-Uptime-Server In Minute",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "redis_uptime_in_seconds", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}