version: "3"
services:
    nginx:
        image: nginx:latest
        ports:
            - 8081:80
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./config/login.html:/opt/login/login.html:ro
            - ./config/error_login.html:/opt/error/error_login.html:ro
            - ./config/one.html:/usr/share/one/index.html:ro
            - ./config/two.html:/usr/share/two/index.html:ro
